2025-07-12 19:02:31,181 [INFO]: 生成批次号: PH25071203，目的仓: 凭祥北投仓
2025-07-12 19:02:31,190 [INFO]: 创建出库记录：裕同 - 批次号：PH25071203
2025-07-12 19:02:31,205 [INFO]: 创建出库记录：富士康 - 批次号：PH25071203
2025-07-12 19:02:31,212 [INFO]: 创建出库记录：捷联达 - 批次号：PH25071203
2025-07-12 19:02:31,220 [INFO]: 创建出库记录：丁乙恒 - 批次号：PH25071203
2025-07-12 19:02:31,227 [INFO]: 创建出库记录：金沃佳 - 批次号：PH25071203
2025-07-12 19:02:31,234 [INFO]: 创建出库记录：长园精密 - 批次号：PH25071203
2025-07-12 19:02:31,242 [INFO]: 创建出库记录：泰塑 - 批次号：PH25071203
2025-07-12 19:02:45,184 [INFO]: 不同批次号数量: 3
2025-07-12 19:02:59,071 [ERROR]: Exception on /outbound/print_selected_records [POST]
Traceback (most recent call last):
  File "C:\Users\杨\Desktop\pythonProject\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\杨\Desktop\pythonProject\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\杨\Desktop\pythonProject\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\杨\Desktop\pythonProject\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\杨\Desktop\pythonProject\app\main\routes.py", line 4980, in print_selected_records
    return render_template('outbound_print_template.html',
  File "C:\Users\杨\Desktop\pythonProject\lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\杨\Desktop\pythonProject\lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\杨\Desktop\pythonProject\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\杨\Desktop\pythonProject\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "c:\Users\杨\Desktop\pythonProject\app\templates\outbound_print_template.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "c:\Users\杨\Desktop\pythonProject\app\templates\base.html", line 522, in top-level template code
    {% block content %}{% endblock %}
  File "c:\Users\杨\Desktop\pythonProject\app\templates\outbound_print_template.html", line 244, in block 'content'
    <td class="text-center">{{ batch_items|sum(attribute='inbound_pallet_count') or 0 }}</td>
  File "C:\Users\杨\Desktop\pythonProject\lib\site-packages\jinja2\async_utils.py", line 48, in wrapper
    return normal_func(*args, **kwargs)
  File "C:\Users\杨\Desktop\pythonProject\lib\site-packages\jinja2\filters.py", line 1336, in sync_do_sum
    return sum(iterable, start)  # type: ignore[no-any-return, call-overload]
jinja2.exceptions.UndefinedError: 'app.models.OutboundRecord object' has no attribute 'inbound_pallet_count'
2025-07-12 19:03:15,802 [ERROR]: Exception on /outbound/print_selected_records [POST]
Traceback (most recent call last):
  File "C:\Users\杨\Desktop\pythonProject\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\杨\Desktop\pythonProject\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\杨\Desktop\pythonProject\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\杨\Desktop\pythonProject\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\杨\Desktop\pythonProject\app\main\routes.py", line 4980, in print_selected_records
    # 统计每个批次的记录数
  File "C:\Users\杨\Desktop\pythonProject\lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\杨\Desktop\pythonProject\lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\杨\Desktop\pythonProject\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\杨\Desktop\pythonProject\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "c:\Users\杨\Desktop\pythonProject\app\templates\outbound_print_template.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "c:\Users\杨\Desktop\pythonProject\app\templates\base.html", line 522, in top-level template code
    {% block content %}{% endblock %}
  File "c:\Users\杨\Desktop\pythonProject\app\templates\outbound_print_template.html", line 244, in block 'content'
    <td class="text-center">{{ batch_items|sum(attribute='inbound_pallet_count') or 0 }}</td>
  File "C:\Users\杨\Desktop\pythonProject\lib\site-packages\jinja2\async_utils.py", line 48, in wrapper
    return normal_func(*args, **kwargs)
  File "C:\Users\杨\Desktop\pythonProject\lib\site-packages\jinja2\filters.py", line 1336, in sync_do_sum
    return sum(iterable, start)  # type: ignore[no-any-return, call-overload]
jinja2.exceptions.UndefinedError: 'app.models.OutboundRecord object' has no attribute 'inbound_pallet_count'
2025-07-12 19:04:36,653 [INFO]: 不同批次号数量: 3
2025-07-12 19:04:46,839 [INFO]: 不同批次号数量: 3
2025-07-12 19:04:51,336 [ERROR]: Exception on /outbound/print_selected_records [POST]
Traceback (most recent call last):
  File "C:\Users\杨\Desktop\pythonProject\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\杨\Desktop\pythonProject\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\杨\Desktop\pythonProject\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\杨\Desktop\pythonProject\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\杨\Desktop\pythonProject\app\main\routes.py", line 4980, in print_selected_records
    # 统计每个批次的记录数
  File "C:\Users\杨\Desktop\pythonProject\lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\杨\Desktop\pythonProject\lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\杨\Desktop\pythonProject\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\杨\Desktop\pythonProject\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "c:\Users\杨\Desktop\pythonProject\app\templates\outbound_print_template.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "c:\Users\杨\Desktop\pythonProject\app\templates\base.html", line 522, in top-level template code
    {% block content %}{% endblock %}
  File "c:\Users\杨\Desktop\pythonProject\app\templates\outbound_print_template.html", line 244, in block 'content'
    <td class="text-center">{{ batch_items|sum(attribute='inbound_pallet_count') or 0 }}</td>
  File "C:\Users\杨\Desktop\pythonProject\lib\site-packages\jinja2\async_utils.py", line 48, in wrapper
    return normal_func(*args, **kwargs)
  File "C:\Users\杨\Desktop\pythonProject\lib\site-packages\jinja2\filters.py", line 1336, in sync_do_sum
    return sum(iterable, start)  # type: ignore[no-any-return, call-overload]
jinja2.exceptions.UndefinedError: 'app.models.OutboundRecord object' has no attribute 'inbound_pallet_count'
2025-07-12 19:05:10,838 [INFO]: 不同批次号数量: 3
2025-07-12 19:08:24,257 [INFO]: 不同批次号数量: 3
2025-07-12 19:15:22,355 [INFO]: 不同批次号数量: 0
2025-07-12 20:11:26,970 [INFO]: 不同批次号数量: 3
2025-07-12 20:11:39,233 [INFO]: 不同批次号数量: 3
2025-07-12 20:11:42,349 [INFO]: 不同批次号数量: 3
2025-07-12 20:11:45,685 [INFO]: 不同批次号数量: 0
2025-07-12 20:11:49,115 [INFO]: 不同批次号数量: 3
2025-07-12 20:12:56,808 [INFO]: 不同批次号数量: 3
2025-07-12 20:14:49,011 [INFO]: 不同批次号数量: 3
2025-07-12 20:14:58,901 [INFO]: 不同批次号数量: 3
2025-07-12 20:17:21,926 [INFO]: 不同批次号数量: 3
2025-07-12 20:17:41,129 [INFO]: 不同批次号数量: 3
2025-07-12 20:20:11,994 [INFO]: 不同批次号数量: 3
2025-07-12 20:21:08,606 [INFO]: 不同批次号数量: 3
2025-07-12 20:21:16,452 [INFO]: 不同批次号数量: 3
2025-07-12 20:25:57,261 [INFO]: 不同批次号数量: 3
2025-07-12 20:27:01,748 [INFO]: 不同批次号数量: 3
2025-07-12 20:29:18,279 [INFO]: 不同批次号数量: 3
2025-07-12 20:29:26,745 [INFO]: 不同批次号数量: 3
2025-07-12 20:30:03,825 [INFO]: 不同批次号数量: 0
2025-07-12 20:30:07,294 [INFO]: 不同批次号数量: 0
2025-07-12 20:31:09,752 [INFO]: 不同批次号数量: 3
2025-07-12 20:33:57,019 [INFO]: 不同批次号数量: 3
2025-07-12 20:36:27,113 [INFO]: 不同批次号数量: 3
2025-07-12 20:37:48,291 [INFO]: 不同批次号数量: 3
2025-07-12 20:44:09,913 [INFO]: 不同批次号数量: 3
2025-07-12 20:44:16,538 [INFO]: 不同批次号数量: 3
2025-07-12 21:24:27,309 [ERROR]: 搜索后端仓库存失败: type object 'Inventory' has no attribute 'warehouse_id'
2025-07-12 21:24:32,763 [ERROR]: 搜索后端仓库存失败: type object 'Inventory' has no attribute 'warehouse_id'
2025-07-12 21:31:23,401 [ERROR]: 搜索后端仓库存失败: type object 'Inventory' has no attribute 'inbound_date'
2025-07-12 21:31:28,625 [ERROR]: 搜索后端仓库存失败: type object 'Inventory' has no attribute 'inbound_date'
2025-07-12 21:51:49,577 [INFO]: 生成批次号: PH25071204，目的仓: 凭祥北投仓
2025-07-12 21:51:49,589 [INFO]: 创建出库记录：新弘智 - 批次号：PH25071204
2025-07-12 21:51:49,605 [INFO]: 创建出库记录：佛山震雄 - 批次号：PH25071204
2025-07-12 21:51:49,614 [INFO]: 创建出库记录：华顶 - 批次号：PH25071204
2025-07-12 21:51:49,623 [INFO]: 创建出库记录：首镭激光 - 批次号：PH25071204
2025-07-12 21:51:49,639 [INFO]: 创建出库记录：烟台富士康 - 批次号：PH25071204
2025-07-12 21:54:05,221 [INFO]: 不同批次号数量: 3
2025-07-12 21:55:26,080 [INFO]: 不同批次号数量: 3
2025-07-12 22:07:19,456 [INFO]: 不同批次号数量: 0
2025-07-12 22:08:00,531 [INFO]: 不同批次号数量: 3
2025-07-12 23:06:07,494 [ERROR]: 搜索后端仓库存失败: type object 'Inventory' has no attribute 'inbound_date'
2025-07-12 23:19:16,424 [ERROR]: 搜索后端仓库存失败: type object 'Inventory' has no attribute 'inbound_date'
2025-07-12 23:21:47,389 [ERROR]: 搜索后端仓库存失败: type object 'Inventory' has no attribute 'inbound_date'
2025-07-12 23:25:53,864 [ERROR]: 搜索后端仓库存失败: type object 'Inventory' has no attribute 'inbound_date'
