2025-07-12 19:02:59,071 [ERROR] app: Exception on /outbound/print_selected_records [POST] [in C:\Users\Ñî\Desktop\pythonProject\lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\Ñî\Desktop\pythonProject\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Ñî\Desktop\pythonProject\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Ñî\Desktop\pythonProject\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Ñî\Desktop\pythonProject\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Ñî\Desktop\pythonProject\app\main\routes.py", line 4980, in print_selected_records
    return render_template('outbound_print_template.html',
  File "C:\Users\Ñî\Desktop\pythonProject\lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Ñî\Desktop\pythonProject\lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Ñî\Desktop\pythonProject\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\Ñî\Desktop\pythonProject\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "c:\Users\Ñî\Desktop\pythonProject\app\templates\outbound_print_template.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "c:\Users\Ñî\Desktop\pythonProject\app\templates\base.html", line 522, in top-level template code
    {% block content %}{% endblock %}
  File "c:\Users\Ñî\Desktop\pythonProject\app\templates\outbound_print_template.html", line 244, in block 'content'
    <td class="text-center">{{ batch_items|sum(attribute='inbound_pallet_count') or 0 }}</td>
  File "C:\Users\Ñî\Desktop\pythonProject\lib\site-packages\jinja2\async_utils.py", line 48, in wrapper
    return normal_func(*args, **kwargs)
  File "C:\Users\Ñî\Desktop\pythonProject\lib\site-packages\jinja2\filters.py", line 1336, in sync_do_sum
    return sum(iterable, start)  # type: ignore[no-any-return, call-overload]
jinja2.exceptions.UndefinedError: 'app.models.OutboundRecord object' has no attribute 'inbound_pallet_count'
2025-07-12 19:03:15,802 [ERROR] app: Exception on /outbound/print_selected_records [POST] [in C:\Users\Ñî\Desktop\pythonProject\lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\Ñî\Desktop\pythonProject\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Ñî\Desktop\pythonProject\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Ñî\Desktop\pythonProject\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Ñî\Desktop\pythonProject\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Ñî\Desktop\pythonProject\app\main\routes.py", line 4980, in print_selected_records
    # Í³¼ÆÃ¿¸öÅú´ÎµÄ¼ÇÂ¼Êý
  File "C:\Users\Ñî\Desktop\pythonProject\lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Ñî\Desktop\pythonProject\lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Ñî\Desktop\pythonProject\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\Ñî\Desktop\pythonProject\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "c:\Users\Ñî\Desktop\pythonProject\app\templates\outbound_print_template.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "c:\Users\Ñî\Desktop\pythonProject\app\templates\base.html", line 522, in top-level template code
    {% block content %}{% endblock %}
  File "c:\Users\Ñî\Desktop\pythonProject\app\templates\outbound_print_template.html", line 244, in block 'content'
    <td class="text-center">{{ batch_items|sum(attribute='inbound_pallet_count') or 0 }}</td>
  File "C:\Users\Ñî\Desktop\pythonProject\lib\site-packages\jinja2\async_utils.py", line 48, in wrapper
    return normal_func(*args, **kwargs)
  File "C:\Users\Ñî\Desktop\pythonProject\lib\site-packages\jinja2\filters.py", line 1336, in sync_do_sum
    return sum(iterable, start)  # type: ignore[no-any-return, call-overload]
jinja2.exceptions.UndefinedError: 'app.models.OutboundRecord object' has no attribute 'inbound_pallet_count'
2025-07-12 19:04:51,336 [ERROR] app: Exception on /outbound/print_selected_records [POST] [in C:\Users\Ñî\Desktop\pythonProject\lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\Ñî\Desktop\pythonProject\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Ñî\Desktop\pythonProject\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Ñî\Desktop\pythonProject\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Ñî\Desktop\pythonProject\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "c:\Users\Ñî\Desktop\pythonProject\app\main\routes.py", line 4980, in print_selected_records
    # Í³¼ÆÃ¿¸öÅú´ÎµÄ¼ÇÂ¼Êý
  File "C:\Users\Ñî\Desktop\pythonProject\lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Ñî\Desktop\pythonProject\lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Ñî\Desktop\pythonProject\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\Ñî\Desktop\pythonProject\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "c:\Users\Ñî\Desktop\pythonProject\app\templates\outbound_print_template.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "c:\Users\Ñî\Desktop\pythonProject\app\templates\base.html", line 522, in top-level template code
    {% block content %}{% endblock %}
  File "c:\Users\Ñî\Desktop\pythonProject\app\templates\outbound_print_template.html", line 244, in block 'content'
    <td class="text-center">{{ batch_items|sum(attribute='inbound_pallet_count') or 0 }}</td>
  File "C:\Users\Ñî\Desktop\pythonProject\lib\site-packages\jinja2\async_utils.py", line 48, in wrapper
    return normal_func(*args, **kwargs)
  File "C:\Users\Ñî\Desktop\pythonProject\lib\site-packages\jinja2\filters.py", line 1336, in sync_do_sum
    return sum(iterable, start)  # type: ignore[no-any-return, call-overload]
jinja2.exceptions.UndefinedError: 'app.models.OutboundRecord object' has no attribute 'inbound_pallet_count'
2025-07-12 21:24:27,309 [ERROR] app: ËÑË÷ºó¶Ë²Ö¿â´æÊ§°Ü: type object 'Inventory' has no attribute 'warehouse_id' [in c:\Users\Ñî\Desktop\pythonProject\app\main\routes.py:11351]
2025-07-12 21:24:32,763 [ERROR] app: ËÑË÷ºó¶Ë²Ö¿â´æÊ§°Ü: type object 'Inventory' has no attribute 'warehouse_id' [in c:\Users\Ñî\Desktop\pythonProject\app\main\routes.py:11351]
2025-07-12 21:31:23,401 [ERROR] app: ËÑË÷ºó¶Ë²Ö¿â´æÊ§°Ü: type object 'Inventory' has no attribute 'inbound_date' [in c:\Users\Ñî\Desktop\pythonProject\app\main\routes.py:11361]
2025-07-12 21:31:28,625 [ERROR] app: ËÑË÷ºó¶Ë²Ö¿â´æÊ§°Ü: type object 'Inventory' has no attribute 'inbound_date' [in c:\Users\Ñî\Desktop\pythonProject\app\main\routes.py:11361]
2025-07-12 23:06:07,494 [ERROR] app: ËÑË÷ºó¶Ë²Ö¿â´æÊ§°Ü: type object 'Inventory' has no attribute 'inbound_date' [in C:\Users\Ñî\Desktop\pythonProject\app\main\routes.py:11361]
2025-07-12 23:19:16,424 [ERROR] app: ËÑË÷ºó¶Ë²Ö¿â´æÊ§°Ü: type object 'Inventory' has no attribute 'inbound_date' [in C:\Users\Ñî\Desktop\pythonProject\app\main\routes.py:11361]
2025-07-12 23:21:47,389 [ERROR] app: ËÑË÷ºó¶Ë²Ö¿â´æÊ§°Ü: type object 'Inventory' has no attribute 'inbound_date' [in c:\Users\Ñî\Desktop\pythonProject\app\main\routes.py:11369]
2025-07-12 23:25:53,864 [ERROR] app: ËÑË÷ºó¶Ë²Ö¿â´æÊ§°Ü: type object 'Inventory' has no attribute 'inbound_date' [in c:\Users\Ñî\Desktop\pythonProject\app\main\routes.py:11369]
